version: "3.7"
services:
  api:
    image: ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REGISTRY_NAME}:${VERSION}
    container_name: api
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul