name: master(cd)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'commit_hash'
        required: true
jobs:
  cd:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p ~/api

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          remote_path: ~/api
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: root
          remote_key: ${{ secrets.KEY }}

      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            cd ~/api
            VERSION=${{ github.event.inputs.version }}
            sed -i "s/VERSION=.*/VERSION=$VERSION/" .env
            docker-compose -f ~/api/docker-compose.yml pull
            docker-compose -f ~/api/docker-compose.yml up --build -d
            docker system prune --all -f